/*
 * GridTools
 *
 * Copyright (c) 2014-2019, ETH Zurich
 * All rights reserved.
 *
 * Please, refer to the LICENSE file in the root directory.
 * SPDX-License-Identifier: BSD-3-Clause
 */
#pragma once
// remove this file once GT is at v2.0

#warning "The use of this header is deprecated, use #include <cpp_bindgen/export.hpp>"

#include <cpp_bindgen/export.hpp>

#define GT_EXPORT_BINDING_WITH_SIGNATURE(...) BINDGEN_EXPORT_BINDING_WITH_SIGNATURE(__VA_ARGS__)
#define GT_EXPORT_BINDING_WITH_SIGNATURE_WRAPPED(...) BINDGEN_EXPORT_BINDING_WITH_SIGNATURE_WRAPPED(__VA_ARGS__)
#define GT_EXPORT_BINDING(...) BINDGEN_EXPORT_BINDING(__VA_ARGS__)
#define GT_EXPORT_GENERIC_BINDING(...) BINDGEN_EXPORT_GENERIC_BINDING(__VA_ARGS__)
#define GT_EXPORT_GENERIC_BINDING_WRAPPED(...) BINDGEN_EXPORT_GENERIC_BINDING_WRAPPED(__VA_ARGS__)

#define GT_EXPORT_BINDING_WITH_SIGNATURE_0(...) BINDGEN_EXPORT_BINDING_WITH_SIGNATURE_0(__VA_ARGS__)
#define GT_EXPORT_BINDING_WITH_SIGNATURE_1(...) BINDGEN_EXPORT_BINDING_WITH_SIGNATURE_1(__VA_ARGS__)
#define GT_EXPORT_BINDING_WITH_SIGNATURE_2(...) BINDGEN_EXPORT_BINDING_WITH_SIGNATURE_2(__VA_ARGS__)
#define GT_EXPORT_BINDING_WITH_SIGNATURE_3(...) BINDGEN_EXPORT_BINDING_WITH_SIGNATURE_3(__VA_ARGS__)
#define GT_EXPORT_BINDING_WITH_SIGNATURE_4(...) BINDGEN_EXPORT_BINDING_WITH_SIGNATURE_4(__VA_ARGS__)
#define GT_EXPORT_BINDING_WITH_SIGNATURE_5(...) BINDGEN_EXPORT_BINDING_WITH_SIGNATURE_5(__VA_ARGS__)
#define GT_EXPORT_BINDING_WITH_SIGNATURE_6(...) BINDGEN_EXPORT_BINDING_WITH_SIGNATURE_6(__VA_ARGS__)
#define GT_EXPORT_BINDING_WITH_SIGNATURE_7(...) BINDGEN_EXPORT_BINDING_WITH_SIGNATURE_7(__VA_ARGS__)
#define GT_EXPORT_BINDING_WITH_SIGNATURE_8(...) BINDGEN_EXPORT_BINDING_WITH_SIGNATURE_8(__VA_ARGS__)
#define GT_EXPORT_BINDING_WITH_SIGNATURE_9(...) BINDGEN_EXPORT_BINDING_WITH_SIGNATURE_9(__VA_ARGS__)

#define GT_EXPORT_BINDING_WITH_SIGNATURE_WRAPPED_0(...) BINDGEN_EXPORT_BINDING_WITH_SIGNATURE_WRAPPED_0(__VA_ARGS__)
#define GT_EXPORT_BINDING_WITH_SIGNATURE_WRAPPED_1(...) BINDGEN_EXPORT_BINDING_WITH_SIGNATURE_WRAPPED_1(__VA_ARGS__)
#define GT_EXPORT_BINDING_WITH_SIGNATURE_WRAPPED_2(...) BINDGEN_EXPORT_BINDING_WITH_SIGNATURE_WRAPPED_2(__VA_ARGS__)
#define GT_EXPORT_BINDING_WITH_SIGNATURE_WRAPPED_3(...) BINDGEN_EXPORT_BINDING_WITH_SIGNATURE_WRAPPED_3(__VA_ARGS__)
#define GT_EXPORT_BINDING_WITH_SIGNATURE_WRAPPED_4(...) BINDGEN_EXPORT_BINDING_WITH_SIGNATURE_WRAPPED_4(__VA_ARGS__)
#define GT_EXPORT_BINDING_WITH_SIGNATURE_WRAPPED_5(...) BINDGEN_EXPORT_BINDING_WITH_SIGNATURE_WRAPPED_5(__VA_ARGS__)
#define GT_EXPORT_BINDING_WITH_SIGNATURE_WRAPPED_6(...) BINDGEN_EXPORT_BINDING_WITH_SIGNATURE_WRAPPED_6(__VA_ARGS__)
#define GT_EXPORT_BINDING_WITH_SIGNATURE_WRAPPED_7(...) BINDGEN_EXPORT_BINDING_WITH_SIGNATURE_WRAPPED_7(__VA_ARGS__)
#define GT_EXPORT_BINDING_WITH_SIGNATURE_WRAPPED_8(...) BINDGEN_EXPORT_BINDING_WITH_SIGNATURE_WRAPPED_8(__VA_ARGS__)
#define GT_EXPORT_BINDING_WITH_SIGNATURE_WRAPPED_9(...) BINDGEN_EXPORT_BINDING_WITH_SIGNATURE_WRAPPED_9(__VA_ARGS__)

#define GT_EXPORT_BINDING_0(...) BINDGEN_EXPORT_BINDING_0(__VA_ARGS__)
#define GT_EXPORT_BINDING_1(...) BINDGEN_EXPORT_BINDING_1(__VA_ARGS__)
#define GT_EXPORT_BINDING_2(...) BINDGEN_EXPORT_BINDING_2(__VA_ARGS__)
#define GT_EXPORT_BINDING_3(...) BINDGEN_EXPORT_BINDING_3(__VA_ARGS__)
#define GT_EXPORT_BINDING_4(...) BINDGEN_EXPORT_BINDING_4(__VA_ARGS__)
#define GT_EXPORT_BINDING_5(...) BINDGEN_EXPORT_BINDING_5(__VA_ARGS__)
#define GT_EXPORT_BINDING_6(...) BINDGEN_EXPORT_BINDING_6(__VA_ARGS__)
#define GT_EXPORT_BINDING_7(...) BINDGEN_EXPORT_BINDING_7(__VA_ARGS__)
#define GT_EXPORT_BINDING_8(...) BINDGEN_EXPORT_BINDING_8(__VA_ARGS__)
#define GT_EXPORT_BINDING_9(...) BINDGEN_EXPORT_BINDING_9(__VA_ARGS__)

#define GT_EXPORT_BINDING_WRAPPED_0(...) BINDGEN_EXPORT_BINDING_WRAPPED_0(__VA_ARGS__)
#define GT_EXPORT_BINDING_WRAPPED_1(...) BINDGEN_EXPORT_BINDING_WRAPPED_1(__VA_ARGS__)
#define GT_EXPORT_BINDING_WRAPPED_2(...) BINDGEN_EXPORT_BINDING_WRAPPED_2(__VA_ARGS__)
#define GT_EXPORT_BINDING_WRAPPED_3(...) BINDGEN_EXPORT_BINDING_WRAPPED_3(__VA_ARGS__)
#define GT_EXPORT_BINDING_WRAPPED_4(...) BINDGEN_EXPORT_BINDING_WRAPPED_4(__VA_ARGS__)
#define GT_EXPORT_BINDING_WRAPPED_5(...) BINDGEN_EXPORT_BINDING_WRAPPED_5(__VA_ARGS__)
#define GT_EXPORT_BINDING_WRAPPED_6(...) BINDGEN_EXPORT_BINDING_WRAPPED_6(__VA_ARGS__)
#define GT_EXPORT_BINDING_WRAPPED_7(...) BINDGEN_EXPORT_BINDING_WRAPPED_7(__VA_ARGS__)
#define GT_EXPORT_BINDING_WRAPPED_8(...) BINDGEN_EXPORT_BINDING_WRAPPED_8(__VA_ARGS__)
#define GT_EXPORT_BINDING_WRAPPED_9(...) BINDGEN_EXPORT_BINDING_WRAPPED_9(__VA_ARGS__)
